MpscBlockingConsumerArrayQueue: fix race writing to blocked field
JCTools/JCTools pull request #336
Opened 2021-03-02 13:16 UTC by philipa

Fix for this race:

```
Consumer in parkUntilNext()         Producer in offerAndWakeup()

casProducerIndex(0, 1)
                                    casProducerIndex(1, 2)
                                    soBlocked(null)
soBlocked(thread)

... spin until timeout

casProducerIndex(1, 0) fails

spinWaitForUnblock() for ever
```

2021-03-02 13:21 UTC, franz1981 requested changes

2021-03-02 13:21 UTC, franz1981 commented on jctools-core/src/main/java/org/jctools/queues/MpscBlockingConsumerArrayQueue.java
> +                        else {
no need to else here

2021-03-02 13:48 UTC, philipa commented on jctools-core/src/main/java/org/jctools/queues/MpscBlockingConsumerArrayQueue.java
> +                        else {
Done.

2021-03-02 13:53 UTC, franz1981 approved these changes
LGTM I haven't yet run the reproducer TBH, but the fix logic looks good

2021-03-03 06:45 UTC, nitsanw commented
Thanks @philipa this is a bad bug and a nice fix! will review and get a release out ASAP

2021-03-03 07:05 UTC, merged